# SYSTEM
url: "https://hci-calendar.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

# SITE
title: HCI Calendar
description: Calendar of submission deadlines and conference dates for HCI and related conferences
message: >-
  Please check corrent information on the conference website.<br/>
  Welcome to edit on <a href="https://github.com/hci-calendar/hci-calendar.github.io">GitHub</a>
keywords: >-
  HCI Calendar,
  HCI, Human Computer Interaction,
  VR, Virtual Reality
copyright: "Copyright (C) HCI Calendar. All rights reserved."

# ALL Calendar Links
links:
  -
    name: HCI
    link: /
  -
    name: VR
    link: /vr/
#  -
#    name: CG
#    link: /cg/

# SEO
google_analytics: UA-80597905-2

# INCLUDE PAGES
include: ['_pages']

# SETTING
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
